"""R2 per-order credit holds: order_credit_holds lifecycle + cache rebuild.

Revision ID: 039_order_credit_holds
Revises: 038_catalog_identity_vertical_slice

CTO-AUTH-ORDER-STATE-R2-PER-ORDER-CREDIT-HOLD-IMPLEMENTATION-2026-09-17.

Self-contained: imports only stdlib/alembic/sqlalchemy — never a runtime
module (historical migrations must not drift with code edits).

Phases inside Alembic's single transactional-DDL transaction:
  P  read-only preflight of EVERY live tenant (C3 state matrix, P12
     binding coverage, P14 exposure-only cache proof) — all tenants must
     pass before ANY write; any failure aborts with zero partial writes.
  D  create order_credit_holds (one lifecycle row per order, UNIQUE
     order_id, no soft-delete, lifecycle shape CHECKs).
  B  backfill: deterministic synthesis from order status x effective
     (non-soft-deleted) payment history per the C3 matrix; synthetic rows
     carry created_by IS NULL and are never re-generated by bootstrap.
  R  rebuild every live binding cache to
        SUM(active hold remaining) + SUM(per-order net credit exposure)
     (per-order aggregation first, retailer SUM second — no MAX).
  V  row-level + aggregate-level verification (interlocked with P14).

Downgrade: forward-only. The lifecycle rows and their audit timestamps are
NOT reconstructible after DROP; restoring pre-039 state requires a backup.
"""
from __future__ import annotations

import re
from typing import Any

import sqlalchemy as sa
from alembic import op

revision = "039_order_credit_holds"
down_revision = "038_catalog_identity_vertical_slice"
branch_labels = None
depends_on = None

TENANT_SCHEMA_RE = re.compile(r"^t_[0-9a-f]{32}$")
LIVE_REGISTRATION_STATUSES = (
    "pending_email_verification",
    "email_verified",
    "provisioning",
    "active",
    "failed",
)
WHOLESALER_ACTIVE_STATUSES = ("active", "provisioning")
HOLD_BEARING_STATUSES = ("confirmed", "partially_paid")
TERMINAL_PAID_STATUSES = ("paid", "fulfilled", "returned")
NO_HOLD_STATUSES = ("draft", "cancelled", "voided")

HOLD_TABLE_DDL = """
            CREATE TABLE {schema}.order_credit_holds (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                order_id UUID NOT NULL
                    CONSTRAINT fk_order_credit_holds_order
                    REFERENCES {schema}.orders(id) ON DELETE RESTRICT,
                amount NUMERIC(12, 2) NOT NULL,
                remaining_amount NUMERIC(12, 2) NOT NULL,
                status VARCHAR(16) NOT NULL DEFAULT 'active',
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                created_by UUID,
                updated_by UUID,
                CONSTRAINT uq_order_credit_holds_order_id UNIQUE (order_id),
                CONSTRAINT ck_order_credit_holds_status CHECK (
                    status IN ('active', 'released', 'settled', 'converted')),
                CONSTRAINT ck_order_credit_holds_amount_positive CHECK (
                    amount > 0),
                CONSTRAINT ck_order_credit_holds_remaining_cap CHECK (
                    remaining_amount <= amount),
                CONSTRAINT ck_order_credit_holds_lifecycle_shape CHECK (
                    (status = 'active' AND remaining_amount > 0)
                    OR (status IN ('released', 'settled', 'converted')
                        AND remaining_amount = 0))
            )
"""
HOLD_ACTIVE_INDEX_DDL = (
    "CREATE INDEX ix_order_credit_holds_active ON {schema}.order_credit_holds "
    "(order_id) WHERE status = 'active'"
)

# Per-order effective payment aggregation (soft-deleted rows are NOT
# history). Reused by preflight, backfill, rebuild and verification.
EFFECTIVE_PER_ORDER = """
            effective_payments AS (
                SELECT p.order_id,
                       COALESCE(SUM(p.amount) FILTER (
                           WHERE p.method IN ('cash', 'transfer')), 0)
                           AS cash_total,
                       COALESCE(SUM(p.amount) FILTER (
                           WHERE p.method = 'credit'), 0)
                           AS credit_total,
                       COUNT(*) FILTER (WHERE p.method = 'credit')
                           AS credit_rows
                FROM {payments} p
                WHERE p.is_deleted IS FALSE
                GROUP BY p.order_id
            )
"""


class PreflightFailure(RuntimeError):
    pass


def upgrade() -> None:
    bind = op.get_bind()
    schemas = _registered_tenants(bind)

    failures: list[str] = []
    per_tenant_state: list[tuple[str, str]] = []
    for schema in schemas:
        try:
            _preflight_tenant(bind, schema)
            wholesaler_id = _wholesaler_for_schema(bind, schema)
            per_tenant_state.append((schema, wholesaler_id))
        except PreflightFailure as exc:
            failures.append(str(exc))
    if failures:
        raise PreflightFailure(
            "039 preflight failed for "
            f"{len(failures)}/{len(schemas)} tenant(s); no writes performed. "
            + " | ".join(failures))

    for schema, _ws in per_tenant_state:
        _create_hold_table(bind, schema)
    for schema, _ws in per_tenant_state:
        _backfill_holds(bind, schema)
    for schema, ws in per_tenant_state:
        _rebuild_binding_cache(bind, schema, ws)
    for schema, ws in per_tenant_state:
        _verify_tenant(bind, schema, ws)


def downgrade() -> None:
    raise RuntimeError(
        "039_order_credit_holds is forward-only: released/settled/converted "
        "lifecycle rows and their audit timestamps are NOT reconstructible "
        "after DROP. Restoring the pre-039 state requires a database backup."
    )


# ---------------------------------------------------------------------------
# Registry (038 precedent)
# ---------------------------------------------------------------------------


def _registered_tenants(bind) -> list[str]:
    if not _table_exists(bind, "public", "tenant_registrations") or not _table_exists(
        bind, "public", "wholesalers"
    ):
        raise PreflightFailure("authoritative tenant registry tables are missing")
    rows = bind.execute(
        sa.text(
            """
            SELECT tr.tenant_schema,
                   ('t_' || replace(w.id::text, '-', '')) AS derived_schema,
                   tr.status AS registration_status,
                   w.status AS wholesaler_status
            FROM public.tenant_registrations tr
            JOIN public.wholesalers w ON w.id = tr.wholesaler_id
            WHERE tr.is_deleted IS FALSE
              AND w.is_deleted IS FALSE
            ORDER BY tr.tenant_schema
            """
        )
    ).mappings()
    schemas: list[str] = []
    for row in rows:
        schema = row["tenant_schema"]
        if not schema or not TENANT_SCHEMA_RE.fullmatch(schema):
            raise PreflightFailure("registered tenant schema is malformed")
        if schema != row["derived_schema"]:
            raise PreflightFailure(
                f"{schema}: registry schema does not match wholesaler identity"
            )
        if (
            row["registration_status"] not in LIVE_REGISTRATION_STATUSES
            or row["wholesaler_status"] not in WHOLESALER_ACTIVE_STATUSES
        ):
            raise PreflightFailure(
                f"{schema}: registered tenant is outside R2 live migration "
                "statuses (same registry contract as 038)"
            )
        if schema not in schemas:
            schemas.append(schema)
    return schemas


def _wholesaler_for_schema(bind, schema: str) -> str:
    row = bind.execute(
        sa.text(
            """
            SELECT w.id::text
            FROM public.tenant_registrations tr
            JOIN public.wholesalers w ON w.id = tr.wholesaler_id
            WHERE tr.tenant_schema = :schema
              AND tr.is_deleted IS FALSE
              AND w.is_deleted IS FALSE
            LIMIT 1
            """
        ),
        {"schema": schema},
    ).first()
    if row is None:
        raise PreflightFailure(f"{schema}: no live wholesaler registration")
    return row[0]


# ---------------------------------------------------------------------------
# Phase P: preflight (read-only, all tenants, all checks, counts reported)
# ---------------------------------------------------------------------------


def _preflight_tenant(bind, schema: str) -> None:
    for table in ("orders", "payments"):
        if not _table_exists(bind, schema, table):
            raise PreflightFailure(f"{schema}.{table} is missing")
    if _table_exists(bind, schema, "order_credit_holds"):
        raise PreflightFailure(
            f"{schema}: partial or pre-existing R2 schema detected "
            "(order_credit_holds already present)"
        )

    ws = _wholesaler_for_schema(bind, schema)
    q_orders = f'"{schema}".orders'
    q_payments = f'"{schema}".payments'
    params = {"ws": ws}

    cross = _count(bind, f"""
        SELECT COUNT(*) FROM {q_orders}
        WHERE is_deleted IS FALSE AND wholesaler_id::text <> :ws
    """, params)
    if cross:
        raise PreflightFailure(
            f"{schema}: {cross} order(s) belong to another wholesaler")

    bad_payments = _count(bind, f"""
        SELECT COUNT(*)
        FROM {q_payments} p
        LEFT JOIN {q_orders} o ON o.id = p.order_id
        WHERE p.is_deleted IS FALSE
          AND (
              p.amount IS NULL OR p.amount <= 0
              -- PostgreSQL numerics also admit NaN/Infinity/-Infinity; NaN
              -- and +Infinity are NOT caught by "amount <= 0" (NaN sorts
              -- above every non-NaN value), so they are named explicitly.
              OR p.amount IN ('NaN'::numeric, 'Infinity'::numeric,
                              '-Infinity'::numeric)
              OR p.method IS NULL
              OR p.method NOT IN ('cash', 'transfer', 'credit')
              OR p.status IS NULL
              OR p.status NOT IN ('pending', 'completed')
              OR o.id IS NULL OR o.is_deleted IS TRUE
              OR o.wholesaler_id::text <> :ws
              OR p.retailer_id IS DISTINCT FROM o.retailer_id
          )
    """, params)
    if bad_payments:
        raise PreflightFailure(
            f"{schema}: {bad_payments} invalid effective payment row(s) "
            "(zero/negative/non-finite amounts, unknown methods or statuses, "
            "orphaned, cross-wholesaler or retailer-mismatched history cannot "
            "be explained)")

    duplicate_credit = _count(bind, f"""
        WITH {EFFECTIVE_PER_ORDER.format(payments=q_payments)}
        SELECT COUNT(*) FROM effective_payments WHERE credit_rows > 1
    """)
    if duplicate_credit:
        raise PreflightFailure(
            f"{schema}: {duplicate_credit} order(s) carry duplicate credit "
            "sales")

    # C3 state matrix — every order's history must be explainable.
    matrix_violations = _count(bind, f"""
        WITH {EFFECTIVE_PER_ORDER.format(payments=q_payments)},
        classified AS (
            SELECT o.id, o.status::text AS status, o.total_amount,
                   COALESCE(e.cash_total, 0) AS cash_total,
                   COALESCE(e.credit_total, 0) AS credit_total,
                   COALESCE(e.credit_rows, 0) AS credit_rows
            FROM {q_orders} o
            LEFT JOIN effective_payments e ON e.order_id = o.id
            WHERE o.is_deleted IS FALSE AND o.wholesaler_id::text = :ws
        )
        SELECT COUNT(*) FROM classified
        WHERE (status = ANY(ARRAY['confirmed', 'partially_paid',
                                  'paid', 'fulfilled', 'returned'])
               AND total_amount <= 0)
           OR (status = 'confirmed'
               AND (cash_total <> 0 OR credit_total <> 0))
           OR (status = 'partially_paid'
               AND (credit_total <> 0
                    OR cash_total <= 0 OR cash_total >= total_amount))
           OR (status = ANY(ARRAY['paid', 'fulfilled', 'returned'])
               AND credit_total > 0
               AND (credit_rows <> 1
                    OR credit_total <> total_amount
                    OR cash_total < 0 OR cash_total > credit_total))
           OR (status = ANY(ARRAY['paid', 'fulfilled', 'returned'])
               AND credit_total = 0
               AND cash_total <> total_amount)
           OR (status = ANY(ARRAY['draft', 'cancelled', 'voided'])
               AND (cash_total <> 0 OR credit_total <> 0))
    """, params)
    if matrix_violations:
        raise PreflightFailure(
            f"{schema}: {matrix_violations} order(s) do not fit the C3 "
            "migration state matrix (unexplainable history is rejected, "
            "never repaired)")

    binding_gaps = _count(bind, f"""
        WITH {EFFECTIVE_PER_ORDER.format(payments=q_payments)},
        exposed AS (
            SELECT DISTINCT o.retailer_id::text AS retailer_id
            FROM {q_orders} o
            LEFT JOIN effective_payments e ON e.order_id = o.id
            WHERE o.is_deleted IS FALSE
              AND o.wholesaler_id::text = :ws
              AND (o.status::text = ANY(ARRAY['confirmed', 'partially_paid'])
                   OR COALESCE(e.credit_total, 0) > 0)
        )
        SELECT COUNT(*) FROM exposed r
        WHERE NOT EXISTS (
            SELECT 1 FROM public.wholesaler_retailer_bindings wrb
            WHERE wrb.retailer_id::text = r.retailer_id
              AND wrb.wholesaler_id::text = :ws
              AND wrb.is_deleted IS FALSE
        )
    """, params)
    if binding_gaps:
        raise PreflightFailure(
            f"{schema}: {binding_gaps} retailer(s) with hold-bearing or "
            "credit-exposed orders lack a live binding")

    # P14: the pre-existing cache must equal the 038 exposure-only formula
    # EXACTLY. Drift is unexplainable data and fails closed; this migration
    # never "repairs" the old cache silently.
    cache_diffs = _count(bind, f"""
        WITH {EFFECTIVE_PER_ORDER.format(payments=q_payments)},
        exposure AS (
            SELECT o.retailer_id::text AS retailer_id,
                   SUM(e.credit_total - e.cash_total) AS exposure_total
            FROM {q_orders} o
            JOIN effective_payments e ON e.order_id = o.id
            WHERE o.is_deleted IS FALSE
              AND o.wholesaler_id::text = :ws
              AND e.credit_total > 0
            GROUP BY o.retailer_id
        )
        SELECT COUNT(*)
        FROM public.wholesaler_retailer_bindings wrb
        LEFT JOIN exposure x ON x.retailer_id = wrb.retailer_id::text
        WHERE wrb.is_deleted IS FALSE
          AND wrb.wholesaler_id::text = :ws
          AND wrb.outstanding_balance
              <> COALESCE(x.exposure_total, 0)::numeric(12, 2)
    """, params)
    if cache_diffs:
        samples = bind.execute(sa.text(f"""
            WITH {EFFECTIVE_PER_ORDER.format(payments=q_payments)},
            exposure AS (
                SELECT o.retailer_id::text AS retailer_id,
                       SUM(e.credit_total - e.cash_total) AS exposure_total
                FROM {q_orders} o
                JOIN effective_payments e ON e.order_id = o.id
                WHERE o.is_deleted IS FALSE
                  AND o.wholesaler_id::text = :ws
                  AND e.credit_total > 0
                GROUP BY o.retailer_id
            )
            SELECT wrb.retailer_id::text, wrb.outstanding_balance::text,
                   COALESCE(x.exposure_total, 0)::text
            FROM public.wholesaler_retailer_bindings wrb
            LEFT JOIN exposure x ON x.retailer_id = wrb.retailer_id::text
            WHERE wrb.is_deleted IS FALSE
              AND wrb.wholesaler_id::text = :ws
              AND wrb.outstanding_balance
                  <> COALESCE(x.exposure_total, 0)::numeric(12, 2)
            LIMIT 5
        """), params).fetchall()
        sample_text = "; ".join(
            f"retailer={s[0]} cache={s[1]} expected_038={s[2]}" for s in samples)
        raise PreflightFailure(
            f"{schema}: P14 cache proof failed for {cache_diffs} binding(s) "
            f"(cache must equal the 038 exposure-only formula exactly); "
            f"samples: {sample_text}")


# ---------------------------------------------------------------------------
# Phase D: DDL
# ---------------------------------------------------------------------------


def _create_hold_table(bind, schema: str) -> None:
    q = f'"{schema}"'
    bind.execute(sa.text(HOLD_TABLE_DDL.format(schema=q)))
    bind.execute(sa.text(HOLD_ACTIVE_INDEX_DDL.format(schema=q)))


# ---------------------------------------------------------------------------
# Phase B: C3 backfill (created_by IS NULL marks the synthetic snapshot)
# ---------------------------------------------------------------------------


def _backfill_holds(bind, schema: str) -> None:
    q_orders = f'"{schema}".orders'
    q_payments = f'"{schema}".payments'
    q_holds = f'"{schema}".order_credit_holds'
    bind.execute(sa.text(f"""
        WITH {EFFECTIVE_PER_ORDER.format(payments=q_payments)}
        INSERT INTO {q_holds}
            (order_id, amount, remaining_amount, status, created_by)
        SELECT o.id,
               o.total_amount,
               CASE WHEN o.status::text IN ('confirmed', 'partially_paid')
                    THEN o.total_amount - COALESCE(e.cash_total, 0)
                    ELSE 0 END,
               CASE
                   WHEN COALESCE(e.credit_total, 0) > 0 THEN 'converted'
                   WHEN o.status::text IN ('confirmed', 'partially_paid')
                       THEN 'active'
                   ELSE 'settled'
               END,
               NULL
        FROM {q_orders} o
        LEFT JOIN effective_payments e ON e.order_id = o.id
        WHERE o.is_deleted IS FALSE
          AND o.status::text IN ('confirmed', 'partially_paid',
                                 'paid', 'fulfilled', 'returned')
    """))


# ---------------------------------------------------------------------------
# Phase R: binding cache rebuild (per-order first, retailer SUM second)
# ---------------------------------------------------------------------------


def _rebuild_binding_cache(bind, schema: str, ws: str) -> None:
    q_orders = f'"{schema}".orders'
    q_payments = f'"{schema}".payments'
    q_holds = f'"{schema}".order_credit_holds'
    params = {"ws": ws}
    bind.execute(sa.text(f"""
        WITH {EFFECTIVE_PER_ORDER.format(payments=q_payments)},
        holds AS (
            SELECT o.retailer_id::text AS retailer_id,
                   SUM(h.remaining_amount) AS hold_total
            FROM {q_holds} h
            JOIN {q_orders} o ON o.id = h.order_id AND o.is_deleted IS FALSE
            WHERE h.status = 'active'
            GROUP BY o.retailer_id
        ),
        exposure AS (
            SELECT o.retailer_id::text AS retailer_id,
                   SUM(e.credit_total - e.cash_total) AS exposure_total
            FROM {q_orders} o
            JOIN effective_payments e ON e.order_id = o.id
            WHERE o.is_deleted IS FALSE
              AND e.credit_total > 0
            GROUP BY o.retailer_id
        )
        UPDATE public.wholesaler_retailer_bindings wrb
        SET outstanding_balance = target.new_balance::numeric(12, 2),
            updated_at = now()
        FROM (
            SELECT r.retailer_id,
                   (COALESCE(h.hold_total, 0)
                    + COALESCE(x.exposure_total, 0)) AS new_balance
            FROM (
                SELECT retailer_id FROM holds
                UNION
                SELECT retailer_id FROM exposure
            ) r
            LEFT JOIN holds h ON h.retailer_id = r.retailer_id
            LEFT JOIN exposure x ON x.retailer_id = r.retailer_id
        ) target
        WHERE wrb.retailer_id::text = target.retailer_id
          AND wrb.wholesaler_id::text = :ws
          AND wrb.is_deleted IS FALSE
    """), params)
    # bindings with no qualifying orders zero out (phantom coverage)
    bind.execute(sa.text(f"""
        UPDATE public.wholesaler_retailer_bindings wrb
        SET outstanding_balance = 0, updated_at = now()
        WHERE wrb.wholesaler_id::text = :ws
          AND wrb.is_deleted IS FALSE
          AND NOT EXISTS (
              SELECT 1 FROM {q_orders} o
              WHERE o.retailer_id = wrb.retailer_id
                AND o.is_deleted IS FALSE
          )
    """), params)


# ---------------------------------------------------------------------------
# Phase V: verification (interlocked with P14)
# ---------------------------------------------------------------------------


def _verify_tenant(bind, schema: str, ws: str) -> None:
    q_orders = f'"{schema}".orders'
    q_payments = f'"{schema}".payments'
    q_holds = f'"{schema}".order_credit_holds'
    params = {"ws": ws}

    row_violations = _count(bind, f"""
        WITH {EFFECTIVE_PER_ORDER.format(payments=q_payments)},
        expected AS (
            SELECT o.id,
                   o.total_amount,
                   CASE WHEN COALESCE(e.credit_total, 0) > 0 THEN 'converted'
                        WHEN o.status::text IN ('confirmed', 'partially_paid')
                            THEN 'active'
                        ELSE 'settled' END AS status,
                   CASE WHEN o.status::text IN ('confirmed', 'partially_paid')
                             AND COALESCE(e.credit_total, 0) = 0
                        THEN o.total_amount - COALESCE(e.cash_total, 0)
                        ELSE 0 END AS remaining
            FROM {q_orders} o
            LEFT JOIN effective_payments e ON e.order_id = o.id
            WHERE o.is_deleted IS FALSE
              AND o.status::text IN ('confirmed', 'partially_paid',
                                     'paid', 'fulfilled', 'returned')
        )
        SELECT COUNT(*) FROM expected ex
        FULL OUTER JOIN {q_holds} h ON h.order_id = ex.id
        WHERE h.id IS NULL
           OR ex.id IS NULL
           OR h.amount <> ex.total_amount
           OR h.remaining_amount <> ex.remaining
           OR h.status <> ex.status
    """, params)
    if row_violations:
        raise PreflightFailure(
            f"{schema}: V-verify row check failed for {row_violations} "
            "lifecycle row(s) (backfill does not match the C3 matrix)")

    aggregate_violations = _count(bind, f"""
        WITH {EFFECTIVE_PER_ORDER.format(payments=q_payments)},
        holds AS (
            SELECT o.retailer_id::text AS retailer_id,
                   SUM(h.remaining_amount) AS hold_total
            FROM {q_holds} h
            JOIN {q_orders} o ON o.id = h.order_id AND o.is_deleted IS FALSE
            WHERE h.status = 'active'
            GROUP BY o.retailer_id
        ),
        exposure AS (
            SELECT o.retailer_id::text AS retailer_id,
                   SUM(e.credit_total - e.cash_total) AS exposure_total
            FROM {q_orders} o
            JOIN effective_payments e ON e.order_id = o.id
            WHERE o.is_deleted IS FALSE AND e.credit_total > 0
            GROUP BY o.retailer_id
        )
        SELECT COUNT(*)
        FROM public.wholesaler_retailer_bindings wrb
        LEFT JOIN holds h ON h.retailer_id = wrb.retailer_id::text
        LEFT JOIN exposure x ON x.retailer_id = wrb.retailer_id::text
        WHERE wrb.is_deleted IS FALSE
          AND wrb.wholesaler_id::text = :ws
          AND wrb.outstanding_balance
              <> (COALESCE(h.hold_total, 0)
                  + COALESCE(x.exposure_total, 0))::numeric(12, 2)
    """, params)
    if aggregate_violations:
        raise PreflightFailure(
            f"{schema}: V-verify aggregate check failed for "
            f"{aggregate_violations} binding(s) (cache != holds + exposure)")

    negatives = _count(
        bind,
        "SELECT COUNT(*) FROM public.wholesaler_retailer_bindings "
        "WHERE is_deleted IS FALSE AND wholesaler_id::text = :ws "
        "AND outstanding_balance < 0",
        params,
    )
    if negatives:
        raise PreflightFailure(
            f"{schema}: {negatives} negative binding cache value(s) remain")


# ---------------------------------------------------------------------------
# catalog helpers
# ---------------------------------------------------------------------------


def _table_exists(bind, schema: str, table: str) -> bool:
    return bool(
        bind.execute(
            sa.text(
                "SELECT 1 FROM information_schema.tables "
                "WHERE table_schema=:schema AND table_name=:table"
            ),
            {"schema": schema, "table": table},
        ).scalar()
    )


def _count(bind, sql: str, params: dict[str, Any] | None = None) -> int:
    return int((bind.execute(sa.text(sql), params or {}).scalar()) or 0)
