"""R2 per-order credit holds: order_credit_holds lifecycle + cache rebuild.

Revision ID: 039_order_credit_holds
Revises: 038_catalog_identity_vertical_slice

CTO-AUTH-ORDER-STATE-R2-PER-ORDER-CREDIT-HOLD-IMPLEMENTATION-2026-09-17.
Tenant-authority closure: CTO-AUTH-MPANGO-PROMOTION-G1-R2E-P1R1-039-AUTHORITY-20260928.

Self-contained: imports only stdlib/alembic/sqlalchemy — never a runtime
module (historical migrations must not drift with code edits).

Phases inside Alembic's single transactional-DDL transaction:
  P  read-only preflight of EVERY live tenant (C3 state matrix, P12
     binding coverage, P14 exposure-only cache proof) — all tenants must
     pass before ANY write; any failure aborts with zero partial writes.
  D  create order_credit_holds (one lifecycle row per order, UNIQUE
     order_id, no soft-delete, lifecycle shape CHECKs).
  B  backfill: deterministic synthesis from order status x effective
     (non-soft-deleted) payment history per the C3 matrix; synthetic rows
     carry created_by IS NULL and are never re-generated by bootstrap.
  R  rebuild every live binding cache to
        SUM(active hold remaining) + SUM(per-order net credit exposure)
     (per-order aggregation first, retailer SUM second — no MAX).
  V  row-level + aggregate-level verification (interlocked with P14).

Authority windows (G1-R2E-P1R1): app-owned tenant objects (orders/payments
reads, order_credit_holds DDL/backfill, cache rebuild joins, verification)
are reached ONLY through the narrowest ``SET ROLE mpango_app`` windows built
on the admin-provisioned one-way capability (GRANT mpango_app TO
mpango_migrate WITH INHERIT FALSE, SET TRUE); every window end — normal,
body-failed, or token-handshake-failed — RESET ROLEs and proves the
migration identity on the same live connection. Catalog existence probes
read pg_catalog, never privilege-filtered information_schema. The public
registry/binding-cache formulae, the C3/P12/P14 semantics and every named
refusal message are unchanged.

Downgrade: forward-only. The lifecycle rows and their audit timestamps are
NOT reconstructible after DROP; restoring pre-039 state requires a backup.
"""
from __future__ import annotations

import re
from typing import Any

import sqlalchemy as sa
from alembic import op

revision = "039_order_credit_holds"
down_revision = "038_catalog_identity_vertical_slice"
branch_labels = None
depends_on = None

TENANT_SCHEMA_RE = re.compile(r"^t_[0-9a-f]{32}$")
LIVE_REGISTRATION_STATUSES = (
    "pending_email_verification",
    "email_verified",
    "provisioning",
    "active",
    "failed",
)
WHOLESALER_ACTIVE_STATUSES = ("active", "provisioning")
HOLD_BEARING_STATUSES = ("confirmed", "partially_paid")
TERMINAL_PAID_STATUSES = ("paid", "fulfilled", "returned")
NO_HOLD_STATUSES = ("draft", "cancelled", "voided")

HOLD_TABLE_DDL = """
            CREATE TABLE {schema}.order_credit_holds (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                order_id UUID NOT NULL
                    CONSTRAINT fk_order_credit_holds_order
                    REFERENCES {schema}.orders(id) ON DELETE RESTRICT,
                amount NUMERIC(12, 2) NOT NULL,
                remaining_amount NUMERIC(12, 2) NOT NULL,
                status VARCHAR(16) NOT NULL DEFAULT 'active',
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                created_by UUID,
                updated_by UUID,
                CONSTRAINT uq_order_credit_holds_order_id UNIQUE (order_id),
                CONSTRAINT ck_order_credit_holds_status CHECK (
                    status IN ('active', 'released', 'settled', 'converted')),
                CONSTRAINT ck_order_credit_holds_amount_positive CHECK (
                    amount > 0),
                CONSTRAINT ck_order_credit_holds_remaining_cap CHECK (
                    remaining_amount <= amount),
                CONSTRAINT ck_order_credit_holds_lifecycle_shape CHECK (
                    (status = 'active' AND remaining_amount > 0)
                    OR (status IN ('released', 'settled', 'converted')
                        AND remaining_amount = 0))
            )
"""
HOLD_ACTIVE_INDEX_DDL = (
    "CREATE INDEX ix_order_credit_holds_active ON {schema}.order_credit_holds "
    "(order_id) WHERE status = 'active'"
)

# Per-order effective payment aggregation (soft-deleted rows are NOT
# history). Reused by preflight, backfill, rebuild and verification.
EFFECTIVE_PER_ORDER = """
            effective_payments AS (
                SELECT p.order_id,
                       COALESCE(SUM(p.amount) FILTER (
                           WHERE p.method IN ('cash', 'transfer')), 0)
                           AS cash_total,
                       COALESCE(SUM(p.amount) FILTER (
                           WHERE p.method = 'credit'), 0)
                           AS credit_total,
                       COUNT(*) FILTER (WHERE p.method = 'credit')
                           AS credit_rows
                FROM {payments} p
                WHERE p.is_deleted IS FALSE
                GROUP BY p.order_id
            )
"""


class PreflightFailure(RuntimeError):
    pass


TENANT_AUTHORITY_ROLE = "mpango_app"


class TenantDDLAuthorityError(RuntimeError):
    """Named refusal: the migration identity cannot lawfully read or alter
    app-owned tenant objects (missing one-way capability, mixed tenant
    ownership, or a SET ROLE leaked from an earlier window)."""


def _handshake_discard_error(bind, purpose: str,
                             reason: str) -> TenantDDLAuthorityError:
    """Build the named error for a connection that cannot be proven safe.

    Returned rather than raised so the caller owns the raise site, and always
    raised WITHOUT ``from ...``/``from None``: the active exception chain --
    the cleanup failure and the original handshake failure -- stays visible
    instead of being suppressed.  The message states plainly whether the
    connection really was invalidated, so a failed ``invalidate()`` can never
    be reported as a successful discard.
    """
    try:
        bind.invalidate()
        detail = ("the migration connection was invalidated and must not be "
                  "reused under any identity")
    except Exception as invalidate_exc:
        # the underlying message is deliberately NOT interpolated: it is
        # outside this boundary's control and could carry a credential or DSN
        # fragment into Alembic stderr / JUnit.  Only fixed neutral wording
        # and the safe exception TYPE identifier are reported (G1-R2E-P1R1R3)
        detail = (
            "invalidation FAILED "
            f"(exception type {type(invalidate_exc).__name__}); "
            "the connection was NOT discarded and must not be reused under "
            "any identity")
    return TenantDDLAuthorityError(
        f"tenant DDL authority window for {purpose!r}: {reason}; {detail}")


def _abort_handshake_window(bind, savepoint, entry_user: str,
                            purpose: str) -> None:
    """Fail-closed cleanup for the SET-success .. token-return gap.

    ``RESET ROLE`` alone is NOT an executable boundary in that gap: when the
    token probe fails SERVER-side the transaction is aborted and every
    statement except ROLLBACK/ROLLBACK TO SAVEPOINT is refused with 25P02, so
    a bare reset would itself raise and restore nothing (measured on
    PostgreSQL 16.15).  This boundary therefore (1) rolls the handshake
    savepoint back to restore a usable transaction, (2) executes ``RESET
    ROLE`` and verifies ``current_user`` on the SAME live connection, and (3)
    performs the enclosing rollback and re-verifies when the identity still
    mismatches -- the rollback is executed, not merely documented.

    A failing cleanup step never degrades into a claim: the raised error
    carries the reason, states whether the connection really was invalidated,
    and is raised without exception-suppression so BOTH the cleanup failure
    and the original handshake failure stay visible.  No token is returned
    from this path and no replacement connection is opened to fake a
    recovery.
    """
    try:
        savepoint.rollback()
    except Exception:
        try:
            bind.rollback()
        except Exception:
            raise _handshake_discard_error(
                bind, purpose,
                "the handshake savepoint could not be rolled back and the "
                "enclosing transaction could not be rolled back either")
    restored = None
    try:
        bind.execute(sa.text("RESET ROLE"))
        restored = bind.execute(sa.text("SELECT current_user")).scalar()
    except Exception:
        try:
            bind.rollback()
            bind.execute(sa.text("RESET ROLE"))
            restored = bind.execute(sa.text("SELECT current_user")).scalar()
        except Exception:
            raise _handshake_discard_error(
                bind, purpose,
                "the migration identity could not be verified after the "
                "handshake savepoint rollback")
    if restored != entry_user:
        try:
            bind.rollback()
            restored = bind.execute(sa.text("SELECT current_user")).scalar()
        except Exception:
            raise _handshake_discard_error(
                bind, purpose,
                f"current_user {entry_user!r} could not be restored and the "
                "enclosing transaction could not be rolled back")
        if restored != entry_user:
            raise _handshake_discard_error(
                bind, purpose,
                "failed to restore current_user "
                f"{entry_user!r} after a failed SET ROLE handshake "
                f"(now {restored!r})")


def _open_tenant_ddl_authority(bind, schemas: list[str], purpose: str):
    """Open the narrowest SET ROLE window for tenant reads/DDL/backfill.

    Returns the pre-window ``current_user`` (the window token) when the
    one-way capability window is required, or ``None`` when the current
    identity already holds direct CREATE authority on every listed tenant
    schema (legacy single-role / superuser shapes) and needs no window.

    Fails closed with a NAMED error before touching any tenant object when
    a previous window's SET ROLE leaked (``current_user != session_user``),
    when tenant schema ownership is mixed, or when the admin-provisioned
    one-way capability (GRANT app TO migrate WITH INHERIT FALSE, SET TRUE)
    is absent.
    """
    identity = bind.execute(sa.text("SELECT current_user, session_user")).fetchone()
    current_user, session_user = identity[0], identity[1]
    if current_user != session_user:
        raise TenantDDLAuthorityError(
            f"tenant DDL authority window for {purpose!r} refused: "
            f"current_user {current_user!r} != session_user "
            f"{session_user!r} — a SET ROLE from an earlier window leaked "
            "and must be reset before any further tenant work"
        )
    authority = bind.execute(sa.text(
        "SELECT n.nspname, has_schema_privilege(current_user, n.nspname, "
        "'CREATE') FROM pg_catalog.pg_namespace n "
        "WHERE n.nspname = ANY(:schemas) ORDER BY n.nspname"
    ), {"schemas": list(schemas)}).fetchall()
    if not authority:
        raise TenantDDLAuthorityError(
            f"tenant DDL authority window for {purpose!r} refused: none of "
            f"the tenant schemas {sorted(schemas)} exist in pg_namespace "
            "(registry/catalog drift)"
        )
    without_create = [row[0] for row in authority if not row[1]]
    if not without_create:
        return None
    with_create = [row[0] for row in authority if row[1]]
    if with_create:
        raise TenantDDLAuthorityError(
            f"tenant DDL authority window for {purpose!r} refused: mixed "
            f"tenant ownership — CREATE held on {with_create} but not on "
            f"{without_create}; sanctioned topologies are uniformly owned"
        )
    can_set = bind.execute(sa.text(
        "SELECT pg_has_role(current_user, :role, 'SET')"
    ), {"role": TENANT_AUTHORITY_ROLE}).scalar()
    if not can_set:
        raise TenantDDLAuthorityError(
            f"tenant DDL authority for {purpose!r} refused: identity "
            f"{current_user!r} holds no CREATE on tenant schema(s) "
            f"{without_create} and cannot SET ROLE "
            f"{TENANT_AUTHORITY_ROLE!r} — the one-way migration tenant-DDL "
            f"capability (GRANT {TENANT_AUTHORITY_ROLE} TO {current_user} "
            "WITH INHERIT FALSE, SET TRUE, applied by the admin in "
            "provisioning phase 1) is absent on this deployment"
        )
    # The SET-success .. token-return gap needs its own exception-safe
    # boundary: the enclosing _tenant_ddl_authority_window ``finally`` is not
    # reached while this function raises, and a bare RESET ROLE cannot run
    # once a server-side handshake error has aborted the transaction.  The
    # handshake therefore runs inside a SAVEPOINT whose rollback restores
    # both transaction usability and the migration identity, and whose
    # failure path is the shared fail-closed cleanup (G1-R2E-P1R1R2).
    savepoint = bind.begin_nested()
    try:
        bind.execute(sa.text(f'SET ROLE "{TENANT_AUTHORITY_ROLE}"'))
        bound = bind.execute(sa.text("SELECT current_user")).scalar()
        if bound != TENANT_AUTHORITY_ROLE:
            raise TenantDDLAuthorityError(
                f"tenant DDL authority window for {purpose!r} refused: SET ROLE "
                f"bound current_user {bound!r}, expected "
                f"{TENANT_AUTHORITY_ROLE!r}"
            )
        savepoint.commit()
    except BaseException:
        _abort_handshake_window(bind, savepoint, current_user, purpose)
        raise
    return current_user


def _close_tenant_ddl_authority(bind, token, purpose: str) -> None:
    """Close the window: RESET ROLE and prove the migration identity is back.

    Called from ``finally``.  The reset is required on the NORMAL path — the
    window body commits its savepoint and the SET ROLE is still in effect —
    and it is executed (as a verified no-op) on the failure path too, where
    the body savepoint rollback has already reverted the role.  Measured on
    PostgreSQL 16.15: an explicit ROLLBACK does revert SET ROLE, so the reset
    is about closing the live window, not about surviving a rollback.
    """
    if token is None:
        return
    bind.execute(sa.text("RESET ROLE"))
    restored = bind.execute(sa.text("SELECT current_user")).scalar()
    if restored != token:
        raise TenantDDLAuthorityError(
            f"tenant DDL authority window for {purpose!r} failed to restore "
            f"current_user {token!r} (now {restored!r})"
        )


def _tenant_ddl_authority_window(bind, schemas: list[str], purpose: str, body) -> None:
    """Run ``body()`` under the narrowest tenant-authority window.

    The body runs inside a SAVEPOINT so that a body failure leaves the
    enclosing Alembic transaction in a usable state for the mandatory
    identity reset (a plain RESET ROLE is refused with 25P02 inside an
    aborted transaction); the original exception is always re-raised and
    Alembic's outer rollback still discards every partial write.
    """
    token = _open_tenant_ddl_authority(bind, schemas, purpose)
    if token is None:
        body()
        return
    try:
        nested = bind.begin_nested()
        try:
            body()
            nested.commit()
        except Exception:
            nested.rollback()
            raise
    finally:
        _close_tenant_ddl_authority(bind, token, purpose)


def upgrade() -> None:
    bind = op.get_bind()
    schemas = _registered_tenants(bind)
    if not schemas:
        return

    per_tenant_state: list[tuple[str, str]] = []

    def _preflight_all() -> None:
        failures: list[str] = []
        for schema in schemas:
            try:
                _preflight_tenant(bind, schema)
                wholesaler_id = _wholesaler_for_schema(bind, schema)
                per_tenant_state.append((schema, wholesaler_id))
            except PreflightFailure as exc:
                failures.append(str(exc))
        if failures:
            raise PreflightFailure(
                "039 preflight failed for "
                f"{len(failures)}/{len(schemas)} tenant(s); no writes performed. "
                + " | ".join(failures))

    # Phase P — every live tenant must pass read-only preflight (inside one
    # window; zero writes of any kind before it completes).
    _tenant_ddl_authority_window(
        bind, schemas, "039 preflight tenant reads", _preflight_all)

    for schema, _ws in per_tenant_state:
        _tenant_ddl_authority_window(
            bind, [schema], f"039 tenant hold table {schema}",
            lambda schema=schema: _create_hold_table(bind, schema))
    for schema, _ws in per_tenant_state:
        _tenant_ddl_authority_window(
            bind, [schema], f"039 tenant backfill {schema}",
            lambda schema=schema: _backfill_holds(bind, schema))
    for schema, ws in per_tenant_state:
        _tenant_ddl_authority_window(
            bind, [schema], f"039 binding cache rebuild {schema}",
            lambda schema=schema, ws=ws: _rebuild_binding_cache(bind, schema, ws))
    for schema, ws in per_tenant_state:
        _tenant_ddl_authority_window(
            bind, [schema], f"039 tenant verification {schema}",
            lambda schema=schema, ws=ws: _verify_tenant(bind, schema, ws))


def downgrade() -> None:
    raise RuntimeError(
        "039_order_credit_holds is forward-only: released/settled/converted "
        "lifecycle rows and their audit timestamps are NOT reconstructible "
        "after DROP. Restoring the pre-039 state requires a database backup."
    )


# ---------------------------------------------------------------------------
# Registry (038 precedent)
# ---------------------------------------------------------------------------


def _registered_tenants(bind) -> list[str]:
    if not _table_exists(bind, "public", "tenant_registrations") or not _table_exists(
        bind, "public", "wholesalers"
    ):
        raise PreflightFailure("authoritative tenant registry tables are missing")
    rows = bind.execute(
        sa.text(
            """
            SELECT tr.tenant_schema,
                   ('t_' || replace(w.id::text, '-', '')) AS derived_schema,
                   tr.status AS registration_status,
                   w.status AS wholesaler_status
            FROM public.tenant_registrations tr
            JOIN public.wholesalers w ON w.id = tr.wholesaler_id
            WHERE tr.is_deleted IS FALSE
              AND w.is_deleted IS FALSE
            ORDER BY tr.tenant_schema
            """
        )
    ).mappings()
    schemas: list[str] = []
    for row in rows:
        schema = row["tenant_schema"]
        if not schema or not TENANT_SCHEMA_RE.fullmatch(schema):
            raise PreflightFailure("registered tenant schema is malformed")
        if schema != row["derived_schema"]:
            raise PreflightFailure(
                f"{schema}: registry schema does not match wholesaler identity"
            )
        if (
            row["registration_status"] not in LIVE_REGISTRATION_STATUSES
            or row["wholesaler_status"] not in WHOLESALER_ACTIVE_STATUSES
        ):
            raise PreflightFailure(
                f"{schema}: registered tenant is outside R2 live migration "
                "statuses (same registry contract as 038)"
            )
        if schema not in schemas:
            schemas.append(schema)
    return schemas


def _wholesaler_for_schema(bind, schema: str) -> str:
    row = bind.execute(
        sa.text(
            """
            SELECT w.id::text
            FROM public.tenant_registrations tr
            JOIN public.wholesalers w ON w.id = tr.wholesaler_id
            WHERE tr.tenant_schema = :schema
              AND tr.is_deleted IS FALSE
              AND w.is_deleted IS FALSE
            LIMIT 1
            """
        ),
        {"schema": schema},
    ).first()
    if row is None:
        raise PreflightFailure(f"{schema}: no live wholesaler registration")
    return row[0]


# ---------------------------------------------------------------------------
# Phase P: preflight (read-only, all tenants, all checks, counts reported)
# ---------------------------------------------------------------------------


def _preflight_tenant(bind, schema: str) -> None:
    for table in ("orders", "payments"):
        if not _table_exists(bind, schema, table):
            raise PreflightFailure(f"{schema}.{table} is missing")
    if _table_exists(bind, schema, "order_credit_holds"):
        raise PreflightFailure(
            f"{schema}: partial or pre-existing R2 schema detected "
            "(order_credit_holds already present)"
        )

    ws = _wholesaler_for_schema(bind, schema)
    q_orders = f'"{schema}".orders'
    q_payments = f'"{schema}".payments'
    params = {"ws": ws}

    cross = _count(bind, f"""
        SELECT COUNT(*) FROM {q_orders}
        WHERE is_deleted IS FALSE AND wholesaler_id::text <> :ws
    """, params)
    if cross:
        raise PreflightFailure(
            f"{schema}: {cross} order(s) belong to another wholesaler")

    bad_payments = _count(bind, f"""
        SELECT COUNT(*)
        FROM {q_payments} p
        LEFT JOIN {q_orders} o ON o.id = p.order_id
        WHERE p.is_deleted IS FALSE
          AND (
              p.amount IS NULL OR p.amount <= 0
              -- PostgreSQL numerics also admit NaN/Infinity/-Infinity; NaN
              -- and +Infinity are NOT caught by "amount <= 0" (NaN sorts
              -- above every non-NaN value), so they are named explicitly.
              OR p.amount IN ('NaN'::numeric, 'Infinity'::numeric,
                              '-Infinity'::numeric)
              OR p.method IS NULL
              OR p.method NOT IN ('cash', 'transfer', 'credit')
              OR p.status IS NULL
              OR p.status NOT IN ('pending', 'completed')
              OR o.id IS NULL OR o.is_deleted IS TRUE
              OR o.wholesaler_id::text <> :ws
              OR p.retailer_id IS DISTINCT FROM o.retailer_id
          )
    """, params)
    if bad_payments:
        raise PreflightFailure(
            f"{schema}: {bad_payments} invalid effective payment row(s) "
            "(zero/negative/non-finite amounts, unknown methods or statuses, "
            "orphaned, cross-wholesaler or retailer-mismatched history cannot "
            "be explained)")

    duplicate_credit = _count(bind, f"""
        WITH {EFFECTIVE_PER_ORDER.format(payments=q_payments)}
        SELECT COUNT(*) FROM effective_payments WHERE credit_rows > 1
    """)
    if duplicate_credit:
        raise PreflightFailure(
            f"{schema}: {duplicate_credit} order(s) carry duplicate credit "
            "sales")

    # C3 state matrix — every order's history must be explainable.
    matrix_violations = _count(bind, f"""
        WITH {EFFECTIVE_PER_ORDER.format(payments=q_payments)},
        classified AS (
            SELECT o.id, o.status::text AS status, o.total_amount,
                   COALESCE(e.cash_total, 0) AS cash_total,
                   COALESCE(e.credit_total, 0) AS credit_total,
                   COALESCE(e.credit_rows, 0) AS credit_rows
            FROM {q_orders} o
            LEFT JOIN effective_payments e ON e.order_id = o.id
            WHERE o.is_deleted IS FALSE AND o.wholesaler_id::text = :ws
        )
        SELECT COUNT(*) FROM classified
        WHERE (status = ANY(ARRAY['confirmed', 'partially_paid',
                                  'paid', 'fulfilled', 'returned'])
               AND total_amount <= 0)
           OR (status = 'confirmed'
               AND (cash_total <> 0 OR credit_total <> 0))
           OR (status = 'partially_paid'
               AND (credit_total <> 0
                    OR cash_total <= 0 OR cash_total >= total_amount))
           OR (status = ANY(ARRAY['paid', 'fulfilled', 'returned'])
               AND credit_total > 0
               AND (credit_rows <> 1
                    OR credit_total <> total_amount
                    OR cash_total < 0 OR cash_total > credit_total))
           OR (status = ANY(ARRAY['paid', 'fulfilled', 'returned'])
               AND credit_total = 0
               AND cash_total <> total_amount)
           OR (status = ANY(ARRAY['draft', 'cancelled', 'voided'])
               AND (cash_total <> 0 OR credit_total <> 0))
    """, params)
    if matrix_violations:
        raise PreflightFailure(
            f"{schema}: {matrix_violations} order(s) do not fit the C3 "
            "migration state matrix (unexplainable history is rejected, "
            "never repaired)")

    binding_gaps = _count(bind, f"""
        WITH {EFFECTIVE_PER_ORDER.format(payments=q_payments)},
        exposed AS (
            SELECT DISTINCT o.retailer_id::text AS retailer_id
            FROM {q_orders} o
            LEFT JOIN effective_payments e ON e.order_id = o.id
            WHERE o.is_deleted IS FALSE
              AND o.wholesaler_id::text = :ws
              AND (o.status::text = ANY(ARRAY['confirmed', 'partially_paid'])
                   OR COALESCE(e.credit_total, 0) > 0)
        )
        SELECT COUNT(*) FROM exposed r
        WHERE NOT EXISTS (
            SELECT 1 FROM public.wholesaler_retailer_bindings wrb
            WHERE wrb.retailer_id::text = r.retailer_id
              AND wrb.wholesaler_id::text = :ws
              AND wrb.is_deleted IS FALSE
        )
    """, params)
    if binding_gaps:
        raise PreflightFailure(
            f"{schema}: {binding_gaps} retailer(s) with hold-bearing or "
            "credit-exposed orders lack a live binding")

    # P14: the pre-existing cache must equal the 038 exposure-only formula
    # EXACTLY. Drift is unexplainable data and fails closed; this migration
    # never "repairs" the old cache silently.
    cache_diffs = _count(bind, f"""
        WITH {EFFECTIVE_PER_ORDER.format(payments=q_payments)},
        exposure AS (
            SELECT o.retailer_id::text AS retailer_id,
                   SUM(e.credit_total - e.cash_total) AS exposure_total
            FROM {q_orders} o
            JOIN effective_payments e ON e.order_id = o.id
            WHERE o.is_deleted IS FALSE
              AND o.wholesaler_id::text = :ws
              AND e.credit_total > 0
            GROUP BY o.retailer_id
        )
        SELECT COUNT(*)
        FROM public.wholesaler_retailer_bindings wrb
        LEFT JOIN exposure x ON x.retailer_id = wrb.retailer_id::text
        WHERE wrb.is_deleted IS FALSE
          AND wrb.wholesaler_id::text = :ws
          AND wrb.outstanding_balance
              <> COALESCE(x.exposure_total, 0)::numeric(12, 2)
    """, params)
    if cache_diffs:
        samples = bind.execute(sa.text(f"""
            WITH {EFFECTIVE_PER_ORDER.format(payments=q_payments)},
            exposure AS (
                SELECT o.retailer_id::text AS retailer_id,
                       SUM(e.credit_total - e.cash_total) AS exposure_total
                FROM {q_orders} o
                JOIN effective_payments e ON e.order_id = o.id
                WHERE o.is_deleted IS FALSE
                  AND o.wholesaler_id::text = :ws
                  AND e.credit_total > 0
                GROUP BY o.retailer_id
            )
            SELECT wrb.retailer_id::text, wrb.outstanding_balance::text,
                   COALESCE(x.exposure_total, 0)::text
            FROM public.wholesaler_retailer_bindings wrb
            LEFT JOIN exposure x ON x.retailer_id = wrb.retailer_id::text
            WHERE wrb.is_deleted IS FALSE
              AND wrb.wholesaler_id::text = :ws
              AND wrb.outstanding_balance
                  <> COALESCE(x.exposure_total, 0)::numeric(12, 2)
            LIMIT 5
        """), params).fetchall()
        sample_text = "; ".join(
            f"retailer={s[0]} cache={s[1]} expected_038={s[2]}" for s in samples)
        raise PreflightFailure(
            f"{schema}: P14 cache proof failed for {cache_diffs} binding(s) "
            f"(cache must equal the 038 exposure-only formula exactly); "
            f"samples: {sample_text}")


# ---------------------------------------------------------------------------
# Phase D: DDL
# ---------------------------------------------------------------------------


def _create_hold_table(bind, schema: str) -> None:
    q = f'"{schema}"'
    bind.execute(sa.text(HOLD_TABLE_DDL.format(schema=q)))
    bind.execute(sa.text(HOLD_ACTIVE_INDEX_DDL.format(schema=q)))


# ---------------------------------------------------------------------------
# Phase B: C3 backfill (created_by IS NULL marks the synthetic snapshot)
# ---------------------------------------------------------------------------


def _backfill_holds(bind, schema: str) -> None:
    q_orders = f'"{schema}".orders'
    q_payments = f'"{schema}".payments'
    q_holds = f'"{schema}".order_credit_holds'
    bind.execute(sa.text(f"""
        WITH {EFFECTIVE_PER_ORDER.format(payments=q_payments)}
        INSERT INTO {q_holds}
            (order_id, amount, remaining_amount, status, created_by)
        SELECT o.id,
               o.total_amount,
               CASE WHEN o.status::text IN ('confirmed', 'partially_paid')
                    THEN o.total_amount - COALESCE(e.cash_total, 0)
                    ELSE 0 END,
               CASE
                   WHEN COALESCE(e.credit_total, 0) > 0 THEN 'converted'
                   WHEN o.status::text IN ('confirmed', 'partially_paid')
                       THEN 'active'
                   ELSE 'settled'
               END,
               NULL
        FROM {q_orders} o
        LEFT JOIN effective_payments e ON e.order_id = o.id
        WHERE o.is_deleted IS FALSE
          AND o.status::text IN ('confirmed', 'partially_paid',
                                 'paid', 'fulfilled', 'returned')
    """))


# ---------------------------------------------------------------------------
# Phase R: binding cache rebuild (per-order first, retailer SUM second)
# ---------------------------------------------------------------------------


def _rebuild_binding_cache(bind, schema: str, ws: str) -> None:
    q_orders = f'"{schema}".orders'
    q_payments = f'"{schema}".payments'
    q_holds = f'"{schema}".order_credit_holds'
    params = {"ws": ws}
    bind.execute(sa.text(f"""
        WITH {EFFECTIVE_PER_ORDER.format(payments=q_payments)},
        holds AS (
            SELECT o.retailer_id::text AS retailer_id,
                   SUM(h.remaining_amount) AS hold_total
            FROM {q_holds} h
            JOIN {q_orders} o ON o.id = h.order_id AND o.is_deleted IS FALSE
            WHERE h.status = 'active'
            GROUP BY o.retailer_id
        ),
        exposure AS (
            SELECT o.retailer_id::text AS retailer_id,
                   SUM(e.credit_total - e.cash_total) AS exposure_total
            FROM {q_orders} o
            JOIN effective_payments e ON e.order_id = o.id
            WHERE o.is_deleted IS FALSE
              AND e.credit_total > 0
            GROUP BY o.retailer_id
        )
        UPDATE public.wholesaler_retailer_bindings wrb
        SET outstanding_balance = target.new_balance::numeric(12, 2),
            updated_at = now()
        FROM (
            SELECT r.retailer_id,
                   (COALESCE(h.hold_total, 0)
                    + COALESCE(x.exposure_total, 0)) AS new_balance
            FROM (
                SELECT retailer_id FROM holds
                UNION
                SELECT retailer_id FROM exposure
            ) r
            LEFT JOIN holds h ON h.retailer_id = r.retailer_id
            LEFT JOIN exposure x ON x.retailer_id = r.retailer_id
        ) target
        WHERE wrb.retailer_id::text = target.retailer_id
          AND wrb.wholesaler_id::text = :ws
          AND wrb.is_deleted IS FALSE
    """), params)
    # bindings with no qualifying orders zero out (phantom coverage)
    bind.execute(sa.text(f"""
        UPDATE public.wholesaler_retailer_bindings wrb
        SET outstanding_balance = 0, updated_at = now()
        WHERE wrb.wholesaler_id::text = :ws
          AND wrb.is_deleted IS FALSE
          AND NOT EXISTS (
              SELECT 1 FROM {q_orders} o
              WHERE o.retailer_id = wrb.retailer_id
                AND o.is_deleted IS FALSE
          )
    """), params)


# ---------------------------------------------------------------------------
# Phase V: verification (interlocked with P14)
# ---------------------------------------------------------------------------


def _verify_tenant(bind, schema: str, ws: str) -> None:
    q_orders = f'"{schema}".orders'
    q_payments = f'"{schema}".payments'
    q_holds = f'"{schema}".order_credit_holds'
    params = {"ws": ws}

    row_violations = _count(bind, f"""
        WITH {EFFECTIVE_PER_ORDER.format(payments=q_payments)},
        expected AS (
            SELECT o.id,
                   o.total_amount,
                   CASE WHEN COALESCE(e.credit_total, 0) > 0 THEN 'converted'
                        WHEN o.status::text IN ('confirmed', 'partially_paid')
                            THEN 'active'
                        ELSE 'settled' END AS status,
                   CASE WHEN o.status::text IN ('confirmed', 'partially_paid')
                             AND COALESCE(e.credit_total, 0) = 0
                        THEN o.total_amount - COALESCE(e.cash_total, 0)
                        ELSE 0 END AS remaining
            FROM {q_orders} o
            LEFT JOIN effective_payments e ON e.order_id = o.id
            WHERE o.is_deleted IS FALSE
              AND o.status::text IN ('confirmed', 'partially_paid',
                                     'paid', 'fulfilled', 'returned')
        )
        SELECT COUNT(*) FROM expected ex
        FULL OUTER JOIN {q_holds} h ON h.order_id = ex.id
        WHERE h.id IS NULL
           OR ex.id IS NULL
           OR h.amount <> ex.total_amount
           OR h.remaining_amount <> ex.remaining
           OR h.status <> ex.status
    """, params)
    if row_violations:
        raise PreflightFailure(
            f"{schema}: V-verify row check failed for {row_violations} "
            "lifecycle row(s) (backfill does not match the C3 matrix)")

    aggregate_violations = _count(bind, f"""
        WITH {EFFECTIVE_PER_ORDER.format(payments=q_payments)},
        holds AS (
            SELECT o.retailer_id::text AS retailer_id,
                   SUM(h.remaining_amount) AS hold_total
            FROM {q_holds} h
            JOIN {q_orders} o ON o.id = h.order_id AND o.is_deleted IS FALSE
            WHERE h.status = 'active'
            GROUP BY o.retailer_id
        ),
        exposure AS (
            SELECT o.retailer_id::text AS retailer_id,
                   SUM(e.credit_total - e.cash_total) AS exposure_total
            FROM {q_orders} o
            JOIN effective_payments e ON e.order_id = o.id
            WHERE o.is_deleted IS FALSE AND e.credit_total > 0
            GROUP BY o.retailer_id
        )
        SELECT COUNT(*)
        FROM public.wholesaler_retailer_bindings wrb
        LEFT JOIN holds h ON h.retailer_id = wrb.retailer_id::text
        LEFT JOIN exposure x ON x.retailer_id = wrb.retailer_id::text
        WHERE wrb.is_deleted IS FALSE
          AND wrb.wholesaler_id::text = :ws
          AND wrb.outstanding_balance
              <> (COALESCE(h.hold_total, 0)
                  + COALESCE(x.exposure_total, 0))::numeric(12, 2)
    """, params)
    if aggregate_violations:
        raise PreflightFailure(
            f"{schema}: V-verify aggregate check failed for "
            f"{aggregate_violations} binding(s) (cache != holds + exposure)")

    negatives = _count(
        bind,
        "SELECT COUNT(*) FROM public.wholesaler_retailer_bindings "
        "WHERE is_deleted IS FALSE AND wholesaler_id::text = :ws "
        "AND outstanding_balance < 0",
        params,
    )
    if negatives:
        raise PreflightFailure(
            f"{schema}: {negatives} negative binding cache value(s) remain")


# ---------------------------------------------------------------------------
# catalog helpers
# ---------------------------------------------------------------------------


def _table_exists(bind, schema: str, table: str) -> bool:
    # pg_catalog, not information_schema: the migration authority must see
    # app-owned tenant tables even though privilege-filtered views hide them
    # (G1-R2E-P1R1 authority contract; genuinely absent tables are still
    # rejected by name through the same call sites).
    return bool(
        bind.execute(
            sa.text(
                "SELECT 1 FROM pg_catalog.pg_class c "
                "JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace "
                "WHERE n.nspname=:schema AND c.relname=:table "
                "AND c.relkind IN ('r', 'p', 'v', 'f')"
            ),
            {"schema": schema, "table": table},
        ).scalar()
    )


def _count(bind, sql: str, params: dict[str, Any] | None = None) -> int:
    return int((bind.execute(sa.text(sql), params or {}).scalar()) or 0)
