#!/usr/bin/env python3
"""Platform Agent Timeout Watchdog - Mpango ERP.

Runs an agent command with an explicit timeout and writes a compact
platform ledger report for pass/fail/timeout outcomes.
"""

import argparse
import os
import subprocess
import sys
import time
from pathlib import Path


FORBIDDEN_PREFIXES = [
    "backend/",
    "frontend/",
    ".github/workflows/",
    ".claude/",
]

FORBIDDEN_SPECIFIC = [
    "docs/ai/PHASE4_FRONTEND_CONTRACT.md",
]

FORBIDDEN_FRAGMENTS = [
    "auth", "rbac", "tenancy", "session", "migration", "payment",
]

VALID_RISK_LEVELS = ["LOW", "MEDIUM", "HIGH", "CRITICAL"]
TIMEOUT_EXIT_CODE = 124


def normalize_path(path):
    return path.replace("\\", "/")


def has_unsafe_path_part(path):
    parts = normalize_path(path).split("/")
    return any(part in ("", ".", "..") for part in parts)


def is_forbidden_path(path):
    normalized = normalize_path(path)

    for prefix in FORBIDDEN_PREFIXES:
        if normalized.startswith(prefix):
            return True, f"matches forbidden prefix '{prefix}'"

    for specific in FORBIDDEN_SPECIFIC:
        if normalized == specific:
            return True, f"matches forbidden specific path '{specific}'"

    for part in normalized.split("/"):
        part_lower = part.lower()
        for fragment in FORBIDDEN_FRAGMENTS:
            if fragment in part_lower:
                return True, f"contains forbidden fragment '{fragment}' in '{part}'"

    return False, None


def validate_report_path(value):
    if not isinstance(value, str) or not value:
        return None, "report path must be a non-empty string"

    normalized = normalize_path(value)
    if os.path.isabs(value) or ":" in normalized.split("/")[0]:
        return normalized, f"report path '{normalized}' must be relative"
    if has_unsafe_path_part(normalized):
        return normalized, f"report path '{normalized}' contains unsafe path part"
    if not normalized.startswith("ai-ledger/platform/"):
        return normalized, f"report path '{normalized}' is not under ai-ledger/platform/"
    if not normalized.endswith(".md"):
        return normalized, f"report path '{normalized}' must end in .md"

    forbidden, reason = is_forbidden_path(normalized)
    if forbidden:
        return normalized, f"forbidden report path '{normalized}' ({reason})"

    return normalized, None


def run_git(repo_path, args):
    try:
        result = subprocess.run(
            ["git"] + args,
            cwd=str(repo_path),
            capture_output=True,
            text=True,
            timeout=30,
        )
    except (subprocess.TimeoutExpired, FileNotFoundError) as exc:
        return 1, "", str(exc)
    return result.returncode, result.stdout.strip(), result.stderr.strip()


def get_branch(repo_path):
    rc, out, _ = run_git(repo_path, ["rev-parse", "--abbrev-ref", "HEAD"])
    return out if rc == 0 else "unknown"


def get_commit(repo_path):
    rc, out, _ = run_git(repo_path, ["rev-parse", "HEAD"])
    return out if rc == 0 else "unknown"


def get_changed_files(repo_path):
    rc, out, _ = run_git(repo_path, ["status", "--porcelain=v1", "-uall"])
    if rc != 0 or not out:
        return []

    changed = []
    for line in out.splitlines():
        if not line:
            continue
        status = line[:2]
        path = line[3:]
        if " -> " in path:
            path = path.split(" -> ", 1)[1]
        changed.append((status, normalize_path(path.strip().strip('"'))))
    return changed


def truncate(text, limit):
    if text is None:
        return ""
    if len(text) <= limit:
        return text
    return text[:limit] + "\n...[truncated]..."


def render_report(
    *,
    phase,
    agent,
    branch,
    commit,
    command,
    timeout_seconds,
    elapsed,
    outcome,
    exit_code,
    changed_files,
    risk,
    stdout,
    stderr,
):
    changed_lines = "\n".join(
        f"- `{status}` `{path}`" for status, path in changed_files
    )
    if not changed_lines:
        changed_lines = "- none"

    command_line = " ".join(command)

    return f"""# Phase {phase}: Agent Timeout Watchdog Report

## Branch

`{branch}`

## Commit

`{commit}`

## Agent

`{agent}`

## Command

`{command_line}`

## Timeout

`{timeout_seconds}` seconds

## Elapsed

`{elapsed:.2f}` seconds

## Outcome

`{outcome}`

## Exit Code

`{exit_code}`

## Modified Files

{changed_lines}

## Tests

- command execution was supervised by `scripts/platform_agent_timeout_watchdog.py`

## Report Path

Generated by watchdog CLI

## Risk

`{risk}`

## Stdout

```text
{stdout}
```

## Stderr

```text
{stderr}
```
"""


def run_command(command, repo_path, timeout_seconds):
    start = time.monotonic()
    proc = subprocess.Popen(
        command,
        cwd=str(repo_path),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    try:
        stdout, stderr = proc.communicate(timeout=timeout_seconds)
        elapsed = time.monotonic() - start
        return proc.returncode, False, elapsed, stdout, stderr
    except subprocess.TimeoutExpired:
        proc.kill()
        stdout, stderr = proc.communicate()
        elapsed = time.monotonic() - start
        return TIMEOUT_EXIT_CODE, True, elapsed, stdout, stderr


def main():
    parser = argparse.ArgumentParser(
        description="Mpango ERP Platform Agent Timeout Watchdog"
    )
    parser.add_argument("--repo", required=True, help="Path to git repository")
    parser.add_argument("--report", required=True, help="Report path")
    parser.add_argument("--phase", required=True, help="Phase label")
    parser.add_argument("--agent", default="opencode", help="Agent/tool name")
    parser.add_argument(
        "--timeout-seconds",
        type=float,
        required=True,
        help="Timeout in seconds",
    )
    parser.add_argument(
        "--risk", choices=VALID_RISK_LEVELS, default="MEDIUM",
        help="Risk classification",
    )
    parser.add_argument(
        "--output-limit",
        type=int,
        default=4000,
        help="Maximum stdout/stderr characters stored in report",
    )
    parser.add_argument(
        "command",
        nargs=argparse.REMAINDER,
        help="Command after --",
    )
    args = parser.parse_args()

    if args.timeout_seconds <= 0:
        print("ERROR: --timeout-seconds must be greater than zero", flush=True)
        sys.exit(1)

    if args.output_limit < 0:
        print("ERROR: --output-limit must be zero or greater", flush=True)
        sys.exit(1)

    command = args.command
    if command and command[0] == "--":
        command = command[1:]
    if not command:
        print("ERROR: command after -- is required", flush=True)
        sys.exit(1)

    report_path, report_error = validate_report_path(args.report)
    if report_error:
        print(f"ERROR: {report_error}", flush=True)
        sys.exit(1)

    repo_path = Path(args.repo).resolve()
    branch = get_branch(repo_path)
    commit = get_commit(repo_path)

    exit_code, timed_out, elapsed, stdout, stderr = run_command(
        command, repo_path, args.timeout_seconds
    )
    outcome = "TIMEOUT" if timed_out else ("PASS" if exit_code == 0 else "FAIL")
    changed_files = get_changed_files(repo_path)

    report = render_report(
        phase=args.phase,
        agent=args.agent,
        branch=branch,
        commit=commit,
        command=command,
        timeout_seconds=args.timeout_seconds,
        elapsed=elapsed,
        outcome=outcome,
        exit_code=exit_code,
        changed_files=changed_files,
        risk=args.risk,
        stdout=truncate(stdout, args.output_limit),
        stderr=truncate(stderr, args.output_limit),
    )

    report_abs = repo_path / report_path
    report_abs.parent.mkdir(parents=True, exist_ok=True)
    report_abs.write_text(report, encoding="utf-8")

    print(f"WATCHDOG OUTCOME: {outcome}", flush=True)
    print(f"Exit code: {exit_code}", flush=True)
    print(f"Report: {report_path}", flush=True)
    sys.exit(exit_code)


if __name__ == "__main__":
    main()
